### ISSUE TITLE
Elasticsearch Setup Issue

### ISSUE THREAD

**Issue by dempti** [aws-quickstart/quickstart-eks-cdk-python#14]
This might be particular to me only I am not quite sure on that. However, with the elasticsearch setup set to true, following issue is observed. 
I might be missing something, but did not find anything related to such in README as well suggesting me to enable `enable a service-linked role`manually
PS: Nothing else has been done and is entirely based on `cdk deploy`

![image](https://user-images.githubusercontent.com/87458408/127796420-cc5dad46-d0e1-48f0-955f-8aa455081a36.png)

**Comment by jasonumiker** [comment]
I have a step to do that both in the manual instructions to add that as well as in the buildspec.yml if you use Codebuild to do it for you instead. You just must have missed that step.

"9. (Only required the first time ES in VPC mode is used in this account) Run aws iam create-service-linked-role --aws-service-name es.amazonaws.com"

and 

"- aws iam create-service-linked-role --aws-service-name es.amazonaws.com || true"
