### ISSUE TITLE
Unable to access kubernetes cluster 

### ISSUE THREAD

**Issue by dempti** [aws-quickstart/quickstart-eks-cdk-python#16]
### NOT A BUG BUT RATHER HELP CALL

I implemented cluster properly using the repository. However, I am **unable to access kubernetes cluster** using the key as well as the role that was associated while creating the cluster and deployment.

Please suggest me how to access it or may be I missed something while deploying the service.
**PS: I have not deployed VPN client based on the repository**

**Comment by jasonumiker** [comment]
You either need to use the bastion to access it (via Systems Manager Session Manger) or to enable the client VPN as it deploys the cluster into private subnets and there is no access from the Internet.

**Comment by jasonumiker** [comment]
Alternatively you can flip the cluster endpoints to be public & private in the EKS console (overriding the secure default configuration) - https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html. Or you can use an existing VPC with something like a site-to-site VPN or DirectConnect to provide access.

**Comment by dempti** [comment]
> You either need to use the bastion to access it (via Systems Manager Session Manger) or to enable the client VPN as it deploys the cluster into private subnets and there is no access from the Internet.

I am unable to use session manager to connect to bastion host as well.
![image](https://user-images.githubusercontent.com/87458408/130340264-4270ebb4-91cc-4907-b38a-e448bf7b32af.png)

Did I miss something during the setup?

**Comment by jasonumiker** [comment]
I was looking through the template and if you choose to use and existing role as the cluster admin (("create_new_cluster_admin_role") == "False") that role is also assigned to the Bastion instance. And _that_ role thus needs to have the SSM policy assigned to it (AmazonSSMManagedInstanceCore) so that the SSM Agent on the Bastion. If you let the template create the role it adds it to the role here. It's a good point that this wasn't made clear - I'll add this to the README.
```
if (self.node.try_get_context("create_new_cluster_admin_role") == "True"):
                cluster_admin_role.add_managed_policy(iam.ManagedPolicy.from_aws_managed_policy_name("AmazonSSMManagedInstanceCore"))
```

**Comment by jasonumiker** [comment]
Updated the README with these instructions when you are brining your own cluster_admin_role

**Comment by jasonumiker** [comment]
Provided the two bits of instructions (it is in a private subnet so you need client VPN or bastion and the IAM role involved being assigned to the bastion and thus needing ec2.amazonaws.com and AmazonSSMManagedInstanceCore on it). I think that this is now resolved - if not let me know and I'll reopen it...
