### ISSUE TITLE
Feature Request: Move to Prometheus Operator for AMP

### ISSUE THREAD

**Issue by jasonumiker** [aws-quickstart/quickstart-eks-cdk-python#38]
Moving to the Prometheus Operator will allow for the CRDs that configure Prometheus to work to collect metrics to send to AMP. It seems that the operator now supports SIGv4 to allow for that.
- https://github.com/prometheus-operator/prometheus-operator/issues/3987

**Comment by pr0PM** [comment]
Hi just want to make sure, does this mean right now AMP won't work with prometheus operator as of now?

**Comment by jasonumiker** [comment]
The Prometheus operator vs just Prometheus deployed via the Helm chart has more features such as looking for CRDs to set up Prometheus to scrape them for you. Today we have a 'just Prometheus' Helm chart - I was asked to switch to the Operator for these features. I'll try to have a look into that over the next week or so...

**Comment by jasonumiker** [comment]
I have just merged the migration from the basic Prometheus Helm Chart to the Prometheus Operator. I also added cpu & memory requests for those things you might run on a Fargate only cluster so the dashboards work (and it is really a best practice to have done it anyway)
