### ISSUE TITLE
ElasticSearch Service Linked Role Required

### ISSUE THREAD

**Issue by luketn** [aws-quickstart/quickstart-eks-cdk-python#4]
Hi, Thanks for the work on this example - I learnt a lot from deploying it. 

One small issue I encountered was that the deployment failed with this error:
```
"ValidationException: Before you can proceed, you must enable a service-linked role to give Amazon ES permissions to access your VPC"
```

I think this happens because it's the first time I'm deploying ElasticSearch to my account.

I used this workaround to overcome the issue (ran at the command line):
```
aws iam create-service-linked-role --aws-service-name es.amazonaws.com
```

I read that this might be tricky to include in the CDK deployment but perhaps we could add a solution like this:
```
const serviceLinkedRole = new cdk.CfnResource(this, "es-service-linked-role", {
  type: "AWS::IAM::ServiceLinkedRole",
  properties: {
    AWSServiceName: "es.amazonaws.com",
    Description: "Role for ES to access resources in my VPC"
  }
});

const esDomain = new es.CfnDomain(this, "es", { ... });

esDomain.node.addDependency(serviceLinkedRole);
```
Ref: https://stackoverflow.com/a/60221491

**Comment by luketn** [comment]
Ah - just noticed you are doing that in the CodeBuild buildspec.yml:
```
aws iam create-service-linked-role --aws-service-name es.amazonaws.com || true
```

Maybe could be also called out in the README as a prerequisite if it can't be part of the CDK script?

**Comment by jasonumiker** [comment]
Sorry to hear that this tripped you up. It is already under Step 8 of the Deploy from your laptop section - and as you saw if you do it from CodeBuild it is covered by the buildspec.yml. I did try to do it with CDK and struggled (hence the other steps/solutions) but that was six months ago and will have another look. Did you test that your example of how to do it above works?

**Comment by luketn** [comment]
Oh - damn! I thought I had read that whole read me. Totally missed that. Thanks!

By the time I had found that CDK code I had already run the cli command so couldn’t test it out. If I run it on a new account I’ll try it.
